# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish
permissions:
  contents: write
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile to JS, HTML and CSS
        shell: bash
        run: |
          npm ci 
          npm run build      

      - name: Deploy to GitHub Pages
        uses: amesIves/github-pages-deploy-action@v4.4.1
        with: 
          folder: dist
